### PR TITLE
Avoid calling the maven-dependency-plugin for all builds

### PR DESCRIPTION
**Pull request by xcoulon**
Only trigger the maven-dependency-plugin when the there's a full build or when the pom.xml is part of the incremental changes
Also, replace calls to deprecated methods and added tests to check that the maven-dependency-plugin is called or not (using the junit:junit:4.10
artifact instead of the plugin itself, which doesn't work unless it has been installed in the local repo at least once before)

### CODE REVIEW

**Comment by fbricon** [comment]
Actually if you're replacing the deprecated method calls, you need to set the minimum m2e version requirement in the manifest (That's 1.4)

**Comment by xcoulon** [comment]
@fbricon good point ! I'm also going to include a plugin version update in the MANIFEST.MF file

**Comment by ianbrandt** [comment]
Published to http://ianbrandt.github.io/m2e-maven-dependency-plugin/.  Thanks for the improvements @xcoulon!

**Comment by xcoulon** [comment]
@ianbrandt thanks to you, too ;-)

**Pull request merged**
